/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GithubLink {
        "mode": 'normal' | 'reverse';
        "url": string;
    }
}
declare global {
    interface HTMLGithubLinkElement extends Components.GithubLink, HTMLStencilElement {
    }
    var HTMLGithubLinkElement: {
        prototype: HTMLGithubLinkElement;
        new (): HTMLGithubLinkElement;
    };
    interface HTMLElementTagNameMap {
        "github-link": HTMLGithubLinkElement;
    }
}
declare namespace LocalJSX {
    interface GithubLink {
        "mode"?: 'normal' | 'reverse';
        "url"?: string;
    }
    interface IntrinsicElements {
        "github-link": GithubLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "github-link": LocalJSX.GithubLink & JSXBase.HTMLAttributes<HTMLGithubLinkElement>;
        }
    }
}
